### ISSUE TITLE
Upgrade to SvelteKit 1.0 and remove old workarounds

### ISSUE THREAD

**Issue by benmccann** [wighawag/sveltejs-adapter-ipfs#10]
There are four issues referred to on the readme currently. Issues 2-4 have been closed. The first part of issue 1 has been addressed as well (output is now relative). It'd be nice to see what still needs to be addressed so that we can close the gap in SvelteKit. After it's been updated we can possibly add the dynamic base path support to SvelteKit, which is probably the last thing that's needed.

**Comment by wighawag** [comment]
After investigation, svelte-kit still need some update to support IPFS
See comment here :  https://github.com/sveltejs/kit/issues/595#issuecomment-1426853991

And here is a reproduction repo showing the issues : https://github.com/bug-reproduction/svelte-kit-static-ipfs

I could try to update `sveltejs-adapter-ipfs` but ideally it should be handled by svelte-kit itself

IPFS is after all just a static server and the only constraint is that the website should support dynamic basepath, which svelte-kit should support as discussed here :  https://github.com/sveltejs/kit/issues/595

This not only for IPFS but for situation where it is not possible to know where the website will be hosted (archive website, etc...)

**Comment by wighawag** [comment]
@benmccann 

I spent some more time on it and it should now be working with sveltekit 1.0

It is available in v0.4.5

It is not full proof though and it only serve as documentation to have this properly fix in sveltekit

The process have been documented in the README but a more detailed explanation can be found in this repo/branch : https://github.com/bug-reproduction/svelte-kit-static-ipfs/tree/fixes#fixes

**Comment by benmccann** [comment]
Thank you!
