### ISSUE TITLE
Dynamic page like /todos/[id] not supported

### ISSUE THREAD

**Issue by anthonygraignic** [wighawag/sveltejs-adapter-ipfs#3]
Hi and thanks for your awesome adapter 🙌🙌

I have an issue when using a dynamic page with a path parameter like `/todos/[id]` in a Svelte Kit website. In dev or with another adapter, it works but with IPFS it's not found or unresolved. See the forked demo repo https://github.com/anthonygraignic/sveltekit-ipfs-demo

Svelte kit is using a filesystem-based router but a hash one seems needed by Fleek/IPFS. Do you have an idea or how to make it work ?

Have a lovely day !

**Comment by wighawag** [comment]
Hi @anthonygraignic thanks for your feedback

With IPFS all files need to be pregenerated, so it is not possible to have fully dynamic url. 

What I do for these, I indeed use location.hash and have app specific code for it.

Maybe it could be better integrated in svelte-kit itself. DId not put much thoughts on it

**Comment by anthonygraignic** [comment]
Thanks for you answer !

I think I will use the specific code with `location.hash` approach for now. And wait for the svelte-kit 1.0 release to make a better integration.
