### ISSUE TITLE
Prerendering now takes place in the build phase

### ISSUE THREAD

**Issue by DougAnderson444** [wighawag/sveltejs-adapter-ipfs#5]
https://github.com/wighawag/sveltejs-adapter-ipfs/blob/fd007574caeca5f4ec28305419f1c14904aa883c/index.js#L25

With `"@sveltejs/kit": "^1.0.0-next.303" ` I am getting this build error:

```cli
> Using sveltejs-adapter-ipfs
> builder.prerender() has been removed. Prerendering now takes place in the build phase — see builder.prerender and builder.writePrerendered
    at Object.prerender (file:///C:/Users/douga/Documents2/code/iframe-wallet-sveltekit/node_modules/@sveltejs/kit/dist/chunks/index4.js:161:10)
    at adapt (/node_modules/sveltejs-adapter-ipfs/index.js:25:18)
    at adapt (/node_modules/@sveltejs/kit/dist/chunks/index4.js:180:8)
    at/node_modules/@sveltejs/kit/dist/cli.js:935:11  
```

**Comment by wighawag** [comment]
Thanks @DougAnderson444 for the issue. Not sure when I ll have time to update it.

In the mean time it might be worth commenting here : https://github.com/sveltejs/kit/issues/595

It seems ipfs / dynamic basepath support is not planned for svelte-kit 1.0 

It would be great if it was.

**Comment by woss** [comment]
Fixed in https://github.com/wighawag/sveltejs-adapter-ipfs/pull/6
