### ISSUE TITLE
remove writeStatic

### ISSUE THREAD

**Issue by DougAnderson444** [wighawag/sveltejs-adapter-ipfs#8]
https://github.com/wighawag/sveltejs-adapter-ipfs/blob/d57da8a6b82c40ab141bf3c27a639d9379a023bc/index.js#L31

When I build with the latest kit, it tells me `writeStatic has been removed`

See: https://github.com/sveltejs/kit/blob/5e0cfcb808ca37eb2543339f1ef5c0904b8a938f/packages/kit/src/core/adapt/builder.js#L154

and

https://github.com/sveltejs/kit/pull/5618

**Comment by joewagner** [comment]
Just found the same issue.  @DougAnderson444 I saw your fork and it's working for me so I opened #9
